#pragma once

#include "common/OrderBook.hpp"
#include "common/Trade.hpp"

#include <vector>

namespace exchange::common {

// Matches incoming orders against a single instrument's OrderBook using
// strict price-time priority. One MatchingEngine owns exactly one
// OrderBook (one symbol).
// notes for why this is single-threaded by design and why
// that is the correct choice for low-latency matching, not a limitation.
// Scaling across symbols is achieved by
// running multiple MatchingEngine instances (one per symbol, potentially
// one per thread/core), never by adding concurrency inside one engine.
class MatchingEngine {
public:
    explicit MatchingEngine(Symbol symbol) : book_(std::move(symbol)) {}

    [[nodiscard]] const OrderBook& book() const noexcept {
        return book_;
    }
    
    // Submits a new order. Attempts to match it immediately against the
    // opposite side of the book; any unfilled remainder rests in the
    // book. Returns every Trade generated by this single submission
    // (zero, one, or many - a large aggressive order can sweep through
    // several resting orders/price levels in one call).
    std::vector<Trade> submitOrder(Order incomingOrder) {
        std::vector<Trade> trades;

        if (incomingOrder.side() == Side::Buy) {
            matchAgainst(incomingOrder, book_.sellLevels(), trades);
        } else {
            matchAgainst(incomingOrder, book_.buyLevels(), trades);
        }

        // Whatever wasn't filled rests in the book at its (possibly
        // updated) remaining quantity.
        if (!incomingOrder.isFullyFilled()) {
            book_.addOrder(std::move(incomingOrder));
        }

        return trades;
    }

    // Cancels a resting order. Returns false if it no longer exists
    // (already filled or already cancelled) - this is a normal outcome,
    // not an error, since cancel-vs-fill races are routine in trading.
    bool cancelOrder(OrderId id) {
        return book_.cancelOrder(id);
    }

    // Modifies a resting order's price and/or quantity.
    //
    // Price-time priority rule: changing price, OR increasing quantity,
    // forfeits time priority - the order is removed and re-inserted as
    // if newly submitted (goes to the back of its new price level's
    // queue, and is immediately re-matched in case the new price now
    // crosses the book). Decreasing quantity alone keeps the order's
    // existing place in its queue, since it isn't gaining an unfair
    // advantage over orders that were already waiting behind it.
    //
    // Returns the trades generated by re-matching, if the modification
    // triggered a price change (empty otherwise). Returns std::nullopt
    // if the order doesn't exist.
    std::optional<std::vector<Trade>> modifyOrder(OrderId id, Price newPrice,
                                                  Quantity newQuantity) {
        auto existing = book_.findOrder(id);
        if (!existing.has_value()) {
            return std::nullopt;
        }

        const Order& current = existing->get();
        const bool priceChanged = current.price() != newPrice;
        const bool quantityIncreased = newQuantity.get() > current.remainingQuantity().get();

        if (priceChanged || quantityIncreased) {
            // Loses time priority: pull it out entirely, then treat it
            // as a brand-new incoming order at the new price/quantity.
            const Symbol symbol = current.symbol();
            const Side side = current.side();
            const Timestamp now = std::chrono::system_clock::now();

            book_.cancelOrder(id);
            Order replacement(id, symbol, side, newPrice, newQuantity, now);
            return submitOrder(std::move(replacement));
        }

        // Quantity decrease only: keep priority, just shrink it in place.
        book_.modifyRestingOrderQuantity(id, newQuantity);
        return std::vector<Trade>{}; // no match triggered, priority preserved
    }

private:
    // Matches 'incoming' against 'oppositeLevels' (the resting side on
    // the other side of the book) in strict price-then-time priority.
    // Templated on the level-map type because BuyLevels and SellLevels
    // are different std::map instantiations (opposite comparators)
    // - this lets one function body serve both directions
    // without duplicating the matching loop.
    template <typename LevelMap>
    void matchAgainst(Order& incoming, LevelMap& oppositeLevels, std::vector<Trade>& trades) {
        auto levelIt = oppositeLevels.begin();

        while (levelIt != oppositeLevels.end() && !incoming.isFullyFilled()) {
            PriceLevel& level = levelIt->second;

            if (!pricesCross(incoming, level.price())) {
                break; // best remaining opposite price no longer crosses - done
            }

            auto orderIt = level.begin();
            while (orderIt != level.end() && !incoming.isFullyFilled()) {
                Order& resting = *orderIt;

                const std::int64_t fillQty =
                    std::min(incoming.remainingQuantity().get(), resting.remainingQuantity().get());
                const Quantity fill(fillQty);

                incoming.applyFill(fill);
                resting.applyFill(fill);

                trades.push_back(makeTrade(incoming, resting, level.price(), fill));

                if (resting.isFullyFilled()) {
                    auto toRemove = orderIt;
                    ++orderIt;
                    level.removeOrder(toRemove);
                    book_.forgetOrder(resting.id()); // keep side-index consistent
                } else {
                    ++orderIt; // partially filled resting order keeps its place
                }
            }

            if (level.empty()) {
                levelIt = oppositeLevels.erase(levelIt);
            } else {
                ++levelIt;
            }
        }
    }

    [[nodiscard]] static bool pricesCross(const Order& incoming, Price oppositePrice) noexcept {
        if (incoming.side() == Side::Buy) {
            return incoming.price().get() >= oppositePrice.get();
        }
        return incoming.price().get() <= oppositePrice.get();
    }

    [[nodiscard]] static Trade makeTrade(const Order& incoming, const Order& resting,
                                         Price tradePrice, Quantity fillQty) {
        const OrderId buyId = (incoming.side() == Side::Buy) ? incoming.id() : resting.id();
        const OrderId sellId = (incoming.side() == Side::Buy) ? resting.id() : incoming.id();

        return Trade(buyId, sellId, incoming.symbol(), tradePrice, fillQty,
                     std::chrono::system_clock::now());
    }

    OrderBook book_;
};

} // namespace exchange::common